Create zh_cn.json
squeek502/AppleSkin pull request #178
Opened 2022-02-13 05:09 UTC by Q2297045667

2022-02-13 07:28 UTC, sagesse-cn requested changes

2022-02-13 07:28 UTC, SAGESSE-CN commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showFoodHealthHudOverlay": "显示估计的健康覆盖",
“显示食用后预计恢复的生命值”

2022-02-13 07:28 UTC, sagesse-cn commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showFoodExhaustionHudUnderlay": "展示底图",
“显示当前的疲劳值”

2022-02-13 07:28 UTC, SAGESSE-CN commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showFoodValuesInTooltip": "在工具提示中显示食物值",
食物值是直译，不准确的

2022-02-13 07:28 UTC, SAGESSE-CN commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showFoodValuesHudOverlayWhenOffhand": "立即展示食物的覆盖物",
“显示副手中食物…”

2022-02-13 07:28 UTC, SAGESSE-CN commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.maxHudOverlayFlashAlpha": "闪烁的HUD图标的最大alpha"
设置状态栏中的闪烁透明度

2022-02-13 07:28 UTC, SAGESSE-CN commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showFoodValuesHudOverlayWhenOffhand": "立即展示食物的覆盖物",
覆盖物是直译，翻译成图层合适

2022-02-13 07:28 UTC, SAGESSE-CN commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showVanillaAnimationsOverlay": "设置HUD图标的动画以匹配Minecraft",
启用和原版匹配图标的动画

2022-02-13 07:32 UTC, sagesse-cn requested changes

2022-02-13 07:32 UTC, sagesse-cn commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showSaturationHudOverlay": "显示饱和度叠加",
不是饱和度，是饱腹度，不是覆盖是图层

2022-02-13 07:38 UTC, SAGESSE-CN commented
Refer to https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki?variant=zh-hk

2022-02-14 14:53 UTC, Q2297045667 commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showSaturationHudOverlay": "显示饱和度叠加",
感谢大佬指点

2022-02-14 14:53 UTC, Q2297045667 commented on resources/assets/appleskin/lang/zh_cn.json
> +  "text.autoconfig.appleskin.option.showSaturationHudOverlay": "显示饱和度叠加",
说实话这个机翻的我还没改完

2022-02-14 16:18 UTC, Q2297045667 reviewed
Perfect text

2022-02-18 01:23 UTC, sagesse-cn approved these changes

2022-02-18 01:31 UTC, squeek502 commented
Thanks! And thanks @sagesse-cn for reviewing.

2022-02-18 01:31 UTC, merged