food overlay now works for food in off hand
squeek502/AppleSkin pull request #65
Opened 2020-05-22 17:19 UTC by LordMZTE

2020-05-22 17:24 UTC, LordMZTE commented
i think its always been annoying that this mod doesnt show the overlay for food in the players offhand so i added that in (food in the main hand is still prioritized) would you like me to add a config option so this can be turned on and off in case youd prefer that?

2020-05-23 00:02 UTC, squeek502 requested changes
Thanks! No config option needed. Just one style nitpick.

2020-05-23 00:02 UTC, squeek502 commented on java/squeek/appleskin/client/HUDOverlayHandler.java
> +		if(!FoodHelper.isFood(heldItem = player.getHeldItemMainhand()))
```suggestion
		ItemStack heldItem = player.getHeldItemMainhand();
		if(!FoodHelper.isFood(heldItem))
```

Not a fan of assignment in conditionals

2020-05-23 00:57 UTC, squeek502 approved these changes

2020-05-23 00:58 UTC, merged

2020-05-23 08:57 UTC, LordMZTE commented
thanks for merging!